title: My Awesome Site
description: A simple Jekyll site with sidebar menu
baseurl: "" # если сайт будет размещён в корне домена, иначе укажите путь
url: "https://kondyubaba.github.io/Content/" # замените на ваш URL
